apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wmxs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wmxs
    app.kubernetes.io/part-of: tkrw-pr712-0075-0043-app
  name: devfile-sample-wmxs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wmxs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wmxs
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-wmxs@sha256:aff4982cc86b6143833228fdc7cfea9daa703c4dc46fc41f50e1ec0c86ecabcf
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
