apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wmxs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-wmxs@sha256:aff4982cc86b6143833228fdc7cfea9daa703c4dc46fc41f50e1ec0c86ecabcf
        name: my-nodejs
        resources: {}
status: {}
